"""I/O layer: transfer engine, orchestration service, verification, ssh-pipe bridge.

Re-exports the public API of the io subpackages so ``from jms.io import X``
keeps working.
"""

from jms.io.service import (
    merge_parts_via_ssh,
    relay_transfer,
    run_transfer,
    sftp_transfer,
)
from jms.io.ssh_pipe import run_bridge
from jms.io.transfer import (
    ChunkPolicy,
    ChunkSplitPolicy,
    DEFAULT_CHUNK_THRESHOLD,
    FileInfo,
    FileTask,
    IOOpener,
    LocalOpener,
    LocalOpenerFactory,
    MIN_CHUNK_SIZE,
    OpenerFactory,
    ProgressCallback,
    RelaySpec,
    SFTP_BUFFER_SIZE,
    SFTP_CHANNEL_TIMEOUT,
    SFTPChannelOpener,
    SFTPClient,
    SFTPOpenerFactory,
    SPOT_CHECK_MAX_ATTEMPTS,
    SPOT_CHECK_SIZE,
    TaskResult,
    TransferSpec,
    _capture_sample,
    _parse_remote_spec,
    _pre_allocate_chunked,
    _spot_check_after_write,
    _spot_check_part_file,
    _worker,
    _write_chunk_once,
    connect_sftp,
    execute_transfer,
    group_parts_by_merge_target,
    list_local_files,
    list_remote_files,
    parse_transfer_spec,
    plan_transfer,
    resolve_local_dst,
    resolve_remote_dst,
)
from jms.io.verify import FileVerifyResult, verify_files

__all__ = [
    "ChunkPolicy",
    "ChunkSplitPolicy",
    "DEFAULT_CHUNK_THRESHOLD",
    "FileInfo",
    "FileTask",
    "FileVerifyResult",
    "IOOpener",
    "LocalOpener",
    "LocalOpenerFactory",
    "MIN_CHUNK_SIZE",
    "OpenerFactory",
    "ProgressCallback",
    "RelaySpec",
    "SFTP_BUFFER_SIZE",
    "SFTP_CHANNEL_TIMEOUT",
    "SFTPChannelOpener",
    "SFTPClient",
    "SFTPOpenerFactory",
    "SPOT_CHECK_MAX_ATTEMPTS",
    "SPOT_CHECK_SIZE",
    "TaskResult",
    "TransferSpec",
    "_capture_sample",
    "_parse_remote_spec",
    "_pre_allocate_chunked",
    "_spot_check_after_write",
    "_spot_check_part_file",
    "_worker",
    "_write_chunk_once",
    "connect_sftp",
    "execute_transfer",
    "group_parts_by_merge_target",
    "list_local_files",
    "list_remote_files",
    "merge_parts_via_ssh",
    "parse_transfer_spec",
    "plan_transfer",
    "relay_transfer",
    "resolve_local_dst",
    "resolve_remote_dst",
    "run_bridge",
    "run_transfer",
    "sftp_transfer",
    "verify_files",
]
